### ISSUE TITLE
definere milepæler til roadmap

### ISSUE THREAD

**Issue by leogasnier** [Altinn/altinn-broker#113]
Oppdateringer av veikart i Github til neste uke:

- Alle elementer som inngår i moderniseringen tagges med program/nye-altinn.
- Noen felter som er viktige å få med er:
- Uker Estimert. For 2024 – 2025 er det tidligere estimert for enkelt tiltak i dette . Det som ligger i prognosearket , bør stemme med hva som er i Github, da vi vil avstemme den faktiske fremdriften mot prognosen på et senere tidspunkt. Finner dere større avvik fordi dere har et bedre grunnlag nå er det viktig at dere gir beskjed om dette (i så fall må vi vurdere å endre prognosen).
- Status (Backlog, levert osv.).
- Progresjon i prosent
- Start og End

```[tasklist]
### Tasks
- [x] Start og End
- [x] Progresjon i prosent
- [x] Status
- [x] Uker estimert
- [x] Tags
- [x] definere milepæler
```

**Comment by leogasnier** [comment]
https://github.com/digdir/roadmap

**Comment by leogasnier** [comment]
Innspill til milepæler ønskes her :) @ToreMasoy @erikhag1 @CWO79 @RagnarFatland-Avanade @tomshag @Ceredron

**Comment by CWO79** [comment]
Teamer opp med @erikhag1 og kommer med forslag :-)

**Comment by leogasnier** [comment]
Opprettet milepæler. De må fylles med epics, features og brukerhistorier (tasks) og milepæler hos andre team som vi er avhengig av.

**Comment by leogasnier** [comment]
Gjenstår: Noen tags i SSD
