### ISSUE TITLE
Avklare bruk av Arkivverkets løsning for digitalarkivet

### ISSUE THREAD

**Issue by ToreMasoy** [Altinn/altinn-broker#122]
[MOL-Systemdokumentasjon-120923-072558.pdf](https://github.com/Altinn/altinn-broker/files/12647232/MOL-Systemdokumentasjon-120923-072558.pdf)
[MOL-Opplasting til mottak-120923-072400.pdf](https://github.com/Altinn/altinn-broker/files/12647230/MOL-Opplasting.til.mottak-120923-072400.pdf)
[MOL-Data-modell i Bevaring-120923-072434.pdf](https://github.com/Altinn/altinn-broker/files/12647233/MOL-Data-modell.i.Bevaring-120923-072434.pdf)
[MOL-Fil struktur i Azure-120923-071952.pdf](https://github.com/Altinn/altinn-broker/files/12647231/MOL-Fil.struktur.i.Azure-120923-071952.pdf)
[MOL-Mottak trusselmodell og risikovurdering-120923-072236.pdf](https://github.com/Altinn/altinn-broker/files/12647234/MOL-Mottak.trusselmodell.og.risikovurdering-120923-072236.pdf)
[MOL-Mottak Arkiv Applikasjon-120923-072057.pdf](https://github.com/Altinn/altinn-broker/files/12647235/MOL-Mottak.Arkiv.Applikasjon-120923-072057.pdf)

**Comment by leogasnier** [comment]
@erikhag1 - status på denne? Fremdeles aktuell eller lukke?

**Comment by leogasnier** [comment]
vurdert
