### ISSUE TITLE
Støtte for varsling via kanaler SMS, e-post, events, API, ..

### ISSUE THREAD

**Issue by leogasnier** [Altinn/altinn-broker#136]
Mulighet til å velge mottakskanal for varsling av forsendelser, slik at jeg kan sikre at mottakeren får varslingen på en måte som er mest praktisk og effektiv for dem.

Vurdere behov for varsling via sms og epost (notification) via brokerforsendelse.

**Comment by RagnarFatland-Avanade** [comment]
Avventer reelt behov.

**Comment by leogasnier** [comment]
Behov er uklart. Kan løses ved å bruke frittstående varsel. Lukker denne og så tar vi det opp om noen melder behov.
