### ISSUE TITLE
Avklare lagring og ansvar > Schrems II

### ISSUE THREAD

**Issue by leogasnier** [Altinn/altinn-broker#14]
Se bla mail fra Oddhild, tidligere DPIA.

Vi må få avklart hva vi har ansvar for og om vi har det behandlingsgrunnlaget som trengs. I tillegg bør vi gå i dialog med spes. politiet og muligvis også Helse-møre (som er potensiell ny kunde) for å avklare hvorvidt de har gjort egne vurderinger, eller når de planlegger å gjøre det. Et mulig utfall er at vi må vurdere å tilby alternativ lagring til azure for de tjenester som handterer data som vurderes som mindre egnet for offentlig sky. Se også NSM sine anbefalinger knyttet til nasjonal sky. Håper vi kan starte med å få gjort en innledende vurdering/kartlegging som kan ligge til grunn når vi skal begynne å tenke på løsningskonsepter i neste sprint.

**Comment by ToreMasoy** [comment]
Denne inngår i den juridiske vurderingen
