### ISSUE TITLE
As is kartlegging pr. tjeneste

### ISSUE THREAD

**Issue by leogasnier** [Altinn/altinn-broker#15]
Tom Sverre: Analyse av trafikk, konfigurasjon/oppsett pr tjeneste.
Kombinasjon av uttrekk fra TUL/serviceengine, statistikk, ++

Dette for å sikre at vi forstår likheter og ulikheter knyttet til tjenestene og kan vurdere riktig fremtidsløsning.

**Comment by tomshag** [comment]
test
