### ISSUE TITLE
Upload processing - Virus Scan

### ISSUE THREAD

**Issue by RagnarFatland-Avanade** [Altinn/altinn-broker#163]
UploadProcessing for uploaded files with Virus Scanning.
Upload file triggers async message to Antimalware solution.
Triggers virus scan of file. 
Result pushed to Broker component API to update status for file.
Future: Publishes Altinn Event for Upload Processing Result.

```[tasklist]
### User Stories
- [ ] https://github.com/Altinn/altinn-broker/issues/219
- [ ] https://github.com/Altinn/altinn-broker/issues/220
- [ ] https://github.com/Altinn/altinn-broker/issues/260
- [ ] https://github.com/Altinn/altinn-broker/issues/284
- [ ] https://github.com/Altinn/altinn-broker/issues/272
```

**Comment by leogasnier** [comment]
Innspill i åpent møte:
[12:25 PM] Jendal, Håkon
Tenker at ende til ende kryptering bør være beste praksis for slike type løsninger. Tilsvarer da slik man gjør det i Norsk helsenett for for eksempel Dialogmeldinger i helsevesenet.
-------------
Videre så kommenteres det at virusscan bør skje på mottakersiden.

Vi må vurdere hva vi krever og hva som skal være opsjoner satt i konfigurasjon av tjenesten, eller instans.

**Comment by RagnarFatland-Avanade** [comment]
Jeg vil si at eventuell opsjon om virusscan må settes på tjenesten, ikke instansnivå. Siden det ellers vil være avsender som styrer både potensielt infisert innhold og om det scannes.

**Comment by RagnarFatland-Avanade** [comment]
Etter møte 21.11.2023 sammen med personer fra Altinn Platform / Notifications, så kom vi frem til at Kafka ikke er aktuelt i denne sammenheng. Internt referat [her](https://digdir.sharepoint.com/:w:/r/sites/PGMeldingsutveksling/Delte%20dokumenter/General/Altinn%20migrering/Formidling/Interne%20M%C3%B8tereferat/20231121%20M%C3%B8tereferat%20-%20Kaffka-oppsett.docx?d=w7f8338fdd0b14189ab7e51e170870718&csf=1&web=1&e=ezhR3F). 

Vi går videre med å analysere ny funksjonalitet i Microsoft Defender for Azure Storage for å se om denne er aktuell som basis.
Eventuelt å benytte/utvide Altinn File-Scan.

**Comment by tomshag** [comment]
1. Pricing information: https://azure.microsoft.com/en-us/pricing/details/defender-for-cloud/

2. Scanning er automatisk når den er satt opp. (https://learn.microsoft.com/en-us/azure/defender-for-cloud/defender-for-storage-malware-scan#set-up-of-malware-scanning)
      a. Er det mulig å sette opp defender til å ikke automatisk scanne, mne istedet scanne basert på "bestilling".
            Svar: fra det jeg har funnet finnes ingen slik mulighet.
            Blobs blir scannet hver gang de har blitt "endret" (on-upload trigger). (https://learn.microsoft.com/en-us/answers/questions/1374275/how-to-trigger-an-on-demand-style-antivirus-scan-w)
            Kommentar: "All upload methods trigger the scan. Modifying a blob is an upload operation and therefore the modified content is scanned after the update."
      b. Det er mulig å sette defender basert på storage account, istedet for subscription. Det burde altså være mulig å la tjenesteeiere ha brokerservice hvor scanning ikke forekommer. Om det er ønskelig å ha brokerservice hvor kun spesifikke filer blir scannet ser ikke dette ut til å være tilgjengelig med Defender for øyeblikket.
      
3. Sjekking av resultat kan gjøres via flere metoder.
      a. Event grid, for eksempel hentet via webhook.
            https://learn.microsoft.com/en-us/azure/event-grid/webhook-event-delivery
      b. Blob storage tag, hentes fra Blob storage.
            https://learn.microsoft.com/en-us/azure/storage/blobs/storage-blob-index-how-to

**Comment by tomshag** [comment]
Maximum filstørrelse som scannes i Azure Defender: 2GB.

Maximum filstørrelse som scannes via Symantec Protection Engine: 30GB 
(muligens finnes det ingen max grense:
https://techdocs.broadcom.com/us/en/symantec-security-software/endpoint-security-and-management/symantec-protection-engine/9-1-0/Configuring-and-Monitoring/specifying-the-maximum-file-or-message-size-to-sca-v128532379-d4995e12564.html#v128532379)
