### ISSUE TITLE
Altinn Broker Arkitekturmodellering AS-IS ver. 1

### ISSUE THREAD

**Issue by leogasnier** [Altinn/altinn-broker#18]
Beskrive as is inkl relevante omgivelser som grunnlag for målbilde og overgangsarkitektur.

Modellen er produsert (se lenke i kommentarer). Gjenstår avklaring av hvor den skal bo i fortsettelsen.

**Comment by leogasnier** [comment]
status 23 mars - samlet eksisterende materiale og sammenstilt.

**Comment by erikhag1** [comment]
og KS

**Comment by leogasnier** [comment]
Modellen bor her inntil videre: https://solutions-no.github.io/models/archi/?view=id-e6d5b64ece904784aa06ed3b80f711f6

**Comment by erikhag1** [comment]
> Modellen bor her inntil videre: https://solutions-no.github.io/models/archi/?view=id-e6d5b64ece904784aa06ed3b80f711f6

Det finnes flere modeller og også en påbegynt wiki, der  as-is dokumentasjon av Altinn Broker inngår i en større sammenheng.  Denne leveransen har handlet om å få på plass en første versjon, som utgangspunkt for videre arbeid. Avklaringer om "hjem", form og farge osv. må tas i neste omgang.

**Comment by ToreMasoy** [comment]
Dokumentasjonen må flyttes til et Altinn repository slik at det blir tilgjengelig for alle i teamet.

**Comment by erikhag1** [comment]
Dokumentasjonen er flyttet til Altinn repo = "ark", og publisert til https://altinn.github.io/ark/messaging/main/index.html
