### ISSUE TITLE
Forklaring for {who} parameteret for Formidlingstjenesten-endepunkter

### ISSUE THREAD

**Issue by AndreasEike** [Altinn/altinn-broker#19]
### Question

Synes det er litt uklart hva "who" parameteret er i sammenheng med formidlingstjenesten opplasting og nedlasting av filer. I dokumentasjonen for meldingsboks "who":

 "'my', or an organization number of an organization the user can represent, or <Reportee.ReporteeId>, where the identified reportee may be a person or organization."

Mens i dokumentasjonen for BrokerService står det litt uklart flere beskrivelser:
![image](https://user-images.githubusercontent.com/46325452/222072431-6991a30f-d2a5-4148-b550-bcfb6136ddcb.png)
![image](https://user-images.githubusercontent.com/46325452/222072547-6b02dd3b-8517-4794-997b-da9a38eb1409.png)

For meg virker det som om who skal være enten org nummer på mottaker i formidlingstjenesten eller org.nr/pers.nr for avsender av filen som lastes opp, kan noen forklare hva verdien til dette parameteret skal være?

**Comment by leogasnier** [comment]
Lukkes da A2 fases ut nå
