### ISSUE TITLE
Tilgang via maskinporten

### ISSUE THREAD

**Issue by Ceredron** [Altinn/altinn-broker#194]
### Description

Vi har i skrivende stund lagd en simulert token som ikke har noe å gjøre med Maskinporten. Endre den til å bruke test-token fra Maskinporten.

**Comment by Ceredron** [comment]
Kode klar, men avventer diskusjon med autorisering for mulige utbedringer.

**Comment by ToreMasoy** [comment]
Diskusjon 5.12. Ingen problemer.
