### ISSUE TITLE
Informasjonsbrev til tjenesteeiere om B4 -> websak

### ISSUE THREAD

**Issue by leogasnier** [Altinn/altinn-broker#197]
Skrive brev til tjenesteeierne med info om B4.
```[tasklist]
### Tasks
- [ ] https://github.com/Altinn/altinn-broker/issues/175
```

**Comment by CWO79** [comment]
Informasjonsbrev er påbegynt: 

https://digdir.sharepoint.com/:w:/r/sites/PGMeldingsutveksling/Delte%20dokumenter/General/Altinn%20migrering/Formidling/Kommunikasjon/Informasjonsbrev%20til%20tjenesteeier%20om%20B4.docx?d=we38259a749af443abb4e086bee57b28e&csf=1&web=1&e=nNsZA4
