### ISSUE TITLE
API for konfigurasjon av Formidlingstjenester (MVP)

### ISSUE THREAD

**Issue by hansdragnes** [Altinn/altinn-broker#201]
**Beskrivelse**

Legg til API for konfigurasjon av formidlingstjenester av tjenesteeiere. Tjenesteeiere skal i første omgang kunne se hvilke tjenester de har registrert, registrere en tjeneste, hente ut informasjon om en tjeneste, endre oppseett av tjeneste og lukke en tjeneste (DEL/soft delete)

API som kan kalles av tjenesteeiere for å administrere tjenestene. 
- [x] GET ALL
- [x] GET SINGLE
- [x] POST

Tjenester skal ha følgende felt per nå:
- [x] Løpenummer/GUID
- [x] OrganizationId
- [x] Maskinporten client id (to be replaced av systembrukerid i endelig versjon)

Endre foreløpig autorisasjonsoppsett til:
- [x] ServiceOwner-kontrolleren gjøres bare tilgjengelig for intern bruk. Azure Access Token generert via CLI i denne, muligens noe annet etter #244 
- [x] Service-kontrolleren gjøres bare tilgjengelig for registrerte tjeneste-eiere med Maskinporten token med scope altinn:broker.admin
- [x] Bare registrerte tjenester kan gjøre andre kall (legg til sjekk mot egen DB)

**Andre momenter**

- [x] Dokumentasjon

**Comment by Ceredron** [comment]
Doumentation: https://github.com/Altinn/altinn-studio-docs/pull/1368

**Comment by Ceredron** [comment]
Relatert til syncing mot A2:
https://github.com/orgs/Altinn/projects/54/views/12?pane=issue&itemId=49088940

Put-endepunkt legges til når vi har oppdaterbare versjoner, dvs her:
*https://github.com/orgs/Altinn/projects/54/views/1?pane=issue&itemId=49815593

**Comment by Ceredron** [comment]
Domenemodellen for tjenester kommer til å videreutvikles i forbindelse med overgangsløsningen.

**Comment by leogasnier** [comment]
Skal denne lukkes @Ceredron ?
