### ISSUE TITLE
Replicate Altinn2 functionality

### ISSUE THREAD

**Issue by Ceredron** [Altinn/altinn-broker#203]
### Title, User role(s), and Users value statement(s)

The user would like to keep using the broker service.

### Description

The vendor would like to easily migrate to a new solution.

```[tasklist]
### Tasks
- [ ] https://github.com/Altinn/altinn-broker/issues/165
```

**Comment by leogasnier** [comment]
Er det noe som gjenstår her eller skal denne lukkes? @Ceredron @RagnarFatland-Avanade @tomshag ?
