### ISSUE TITLE
Altinn Events for system events

### ISSUE THREAD

**Issue by RagnarFatland-Avanade** [Altinn/altinn-broker#223]
Altinn Events skal benyttes for å publisere events for forskjellige hendelser i Forsendelsesprosessen.
Broker må derfor integrere seg mot denne komponenten.

Forhåndskrav:

- [x] Skriv om til å bruke Altinn test token
- [x] Implementer mot ressursregisteret
- [x] Integrer mot autorisasjon

Hendelser:

- [x] Fil Lastet opp OK (begynner prossessering)
- [x] Fil ikke lastet opp OK
- [x] Fil feilet Upload Processing
- [x] En mottaker har utført ConfirmDownload
- [x] Alle mottakere har utført ConfirmDownload
- [ ] Filen er sanert grunnet alle mottakere har bekreftet
- [ ] Filen er sanert grunnet at saneringstidspunkt er sanert

**Comment by Ceredron** [comment]
Bør komme etter Party-ID API integreringen.

**Comment by Ceredron** [comment]
https://github.com/Altinn/altinn-broker/issues/191

**Comment by Ceredron** [comment]
Vi må sikre at kunden vet at webhookene de mottar kommer fra oss og ingen andre. Vi kan gjøre dette ved å bruke en delt hemmelighet, det vil si en enkel token/string som vi legger på alle våre kall i et parameter (query?). Vi bør forsikre oss om at dette, eller noe tilsvarende, er innebygget i Altinn Events. Hvis ikke bør vi lage det.

**Comment by Ceredron** [comment]
> Vi må sikre at kunden vet at webhookene de mottar kommer fra oss og ingen andre. Vi kan gjøre dette ved å bruke en delt hemmelighet, det vil si en enkel token/string som vi legger på alle våre kall i et parameter (query?). Vi bør forsikre oss om at dette, eller noe tilsvarende, er innebygget i Altinn Events. Hvis ikke bør vi lage det.

Løses av Altinn Events

**Comment by Ceredron** [comment]
Finn en god måte å dokumentere det i OpenAPI spec.. Evaluer støtte for webhooks i OpenAPI 3.1.

**Comment by Ceredron** [comment]
Forhåndskrav:

 Skriv om til å bruke Altinn test token
 Kall må inkludere altinn:events scopes
 Implementer mot ressursregisteret
