### ISSUE TITLE
Alternative løsningskonsepter/hypoteser

### ISSUE THREAD

**Issue by leogasnier** [Altinn/altinn-broker#24]
som kan "utfordre" eller stressteste Hennings løsningsforslag. Se på fremoverkompabilitet.
Feks. 
Kan formidling være en gjenbrukbar "studio-app" hvor vi lager mvp, og aktiviserer A3 communityet i videre arbeid?
Kan integrasjon og "varsling" løses gjennom dialogporten?
Kan eFormidling spille en rolle?
Kan formidlingstjenesten sine tjenester flyttes til data.altinn?

**Comment by leogasnier** [comment]
DoD: korte overordnede beskrivelser av hvordan vi kan løse fremtidens formidlingstjeneste.
- AS IS ivaretas.
- Mulig å bygge videre på
- Behovsdekning
- Etterlevelse
- Gjennomførbarhet.

**Comment by leogasnier** [comment]
5 skisser klar - invitere teamet til WS for å se på skissene.

**Comment by erikhag1** [comment]
Foreløpig rapport  per 24. mai 23:

Dette er en ganske stor oppgave. Jeg har har presentert en veldig prematur oversikt over veier å gå, men da uten å gå inn på spesifikke konsepter. Det har vært mye annet, men jeg har nå rukket å jobbe noe mer med det og holder på å strukturere en liste over spesifikke, overordnede konsepter.  Listen er lengre enn jeg liker, men jeg snakker stadig med ChatGPT om hvordan dette kan struktureres bedre;) Jeg har også begynt å jobbe med "underordnede konsepter" , så langt innen temaet adressering. 

Bør denne oppgaven brytes opp? Jeg tenker det, men er ikke ferdigtenkt på hvordan...

**Comment by leogasnier** [comment]
Forankres mot data.altinn, dialogporten, og sjefsarkitekt som et minimum. Gjerne også eFormidling.
