### ISSUE TITLE
Utvid filsøk med RecipientStatus

### ISSUE THREAD

**Issue by RagnarFatland-Avanade** [Altinn/altinn-broker#245]
### Description

Som mottaker ønsker jeg å kunne søke etter filer basert på min Recipientstatus via API, slik at jeg kan begrense søket til kun å gi meg liste over de filer basert på mitt forhold til dem.
Det mest aktuelle bruksområdet er når jeg ønsker å få en liste med filer jeg ikke har hentet ned selv, ved å bruke RecipientFileStatus = Initialized.
Filsøket implementert i #165 tillater oss bare å søke etter FileStatus, og dersom vi er flere mottakere vil ikke den endre seg vekk fra Published før alle har kjørt ConfirmDownloaded, noe som krever at jeg må holde kontroll på min side for å filtrere vekk filer jeg allerede har lastet ned.

### Acceptance Criterias

- GetFiles; GET broker/api/v1/file med parameter satt for ReceipientFileStatus filtrerer korrekt for ReceipientFileStatus for kallende mottaker.

**Comment by tomshag** [comment]
Siden dette er et så fundamentalt søk, kunne det vært en ide å ha det som et eget get-kall mot sitt eget endepunkt, for eksempel 
/broker/api/v1/file/pending 
eller no sånt?

**Comment by RagnarFatland-Avanade** [comment]
Etter diskusjon:
Vi utvider eksisterende GetFiles med ReceipientFileStatus som parameter
Setter default verdier på:
 - Filestatus = Published
 - ReceipientFileStatus = Initialized

**Comment by RagnarFatland-Avanade** [comment]
Implementere uten default-verdier på Status-feltene da det begrenset søkemulighetene unødvendig.
Ikke satt felt = ikke filtrer på dette feltet.
