### ISSUE TITLE
Uttekk som viser alle systemer som konsumerer broker

### ISSUE THREAD

**Issue by leogasnier** [Altinn/altinn-broker#246]
I forbindelse med dialogen med tjenesteeiere rundt migreringsplan så trenger både vi og de oversikt. Liste opp alle konsumenter av formidlings-api det siste året basert på systemID/api-nøkkel, pr. api inkl volum? (må få opp en mapping mellom system og systemID da...)?

Ønsket output: Så komplett og detaljert som mulig liste over de virksomhetene og SBS som konsumerer broker apis

**Comment by tomshag** [comment]
Spørringen må hente ut all data fra Authentication.Request tabell hvor vi desverre kun har 6 måneder med data og svært dårlig indeksering.

Jeg henter for øyeblikket ut rå-dataen som trengs som så kan kobles opp mot System / Api nøkkel osv.

**Comment by leogasnier** [comment]
Ok, om det blir problematisk så kan jeg muligvis få rådataene direkte fra ER, bare si fra!

**Comment by tomshag** [comment]
Har lastet opp uttrekk her:
https://digdir.sharepoint.com/:f:/r/sites/PGMeldingsutveksling/Delte%20dokumenter/General/Altinn%20migrering/Uttrekk/Uttrekk%20Bruk%20av%20BrokerService%206%20m%C3%A5neder?csf=1&web=1&e=j2tmrC

Inneholder antall operasjoner gjort per organisasjonsnr iløpet av de siste 6 månedene.
Har ikke tatt høyde for hvilken dato de er kjørt, det er kun full data for hele perioden. (Ellers pleier det bli ekstremt mange rader.)

**Comment by CWO79** [comment]
@leogasnier kan denne lukkes?

**Comment by leogasnier** [comment]
Ja! Done!
