### ISSUE TITLE
Overgangsløsning A2: Opprett BrokerBridge-komponent

### ISSUE THREAD

**Issue by RagnarFatland-Avanade** [Altinn/altinn-broker#250]
Opprett BrokerBridge-komponenten i Altinn 2 kodebasen, denne skal kun kalles direkte i kode, så man trenger ikke service fasader/WCF hosting oppsett.

- [ ] Config-verdi legges til i Altinn.Config for å angi om angitte Formidlingstjenester er Synkroniserte
  - For eksempel: SyncronizedBrokerServiceHome(ServiceCode, ServiceEditionCode) => Altinn2, Altinn3_<resurceid> (bruk feks tuple elns).
 - [ ] public metode som BrokerBridge.IsBrokerServiceSyncronized som kan kalles for å avgjøre om en gitt formidlingstjeneste er synkronisert som benytter config-verdien over.
- [ ] Feature-toggle må opprettes slik at Kall til BrokerBridge kan skrus av/på på normalt vis i Altinn 2.
  
- [ ] Opprett basis skall for operasjonene, bruk egne issues for å tracke/utviklede konkrete operasjonene.
    - CheckIfAvailableFiles
    - GetAvailbleFiles
    - InitiateBrokerService
    - GetFileDataByReference
    - UploadFile
    - DownloadFile
    - ConfirmDownloaded
    - GetReceipt

**Comment by tomshag** [comment]
Har gjort denne endringen i TT02 og lagt inn en pull request her 
https://dev.azure.com/digdir/Altinn/_git/Altinn/pullrequest/6631
til Altinn Release 24.2 da jeg antar at 24.1 er i code freeze etter 09.01.2024.
