### ISSUE TITLE
Overgangsløsning A2: BrokerBridge.GetAvailableFiles + HasAvailableFiles

### ISSUE THREAD

**Issue by RagnarFatland-Avanade** [Altinn/altinn-broker#251]
Implementer følgende metoder i BrokerBridge, med mapping mellom Altinn 2 datamodell og Altinn 3 datamodell.
 - [ ] GetAvailableFiles
    Kaller GET broker/api/legacy/v1/file
 -  [ ] CheckIfAvailableFiles
   Skal kalle GET broker/api/legacy/v1/file med parametre; status = Published, recipientfilestatus = Initialized.
 
Siden disse er såpass like bør nok GetAvailableFiles implementeres først, og CheckIfAvailableFiles kan deretter gjenbruke 
denne.

Anbefaler at denne utvikles etter/sammen med #252 da denne vil også ha behov for samme mapping av objekt mellom A3 og A2.

**Comment by RagnarFatland-Avanade** [comment]
CheckIfAvailableFiles har avhengighet til #245

**Comment by tomshag** [comment]
CheckIfAvailableFiles mottar også en liste med mottakere. det er et kall som krever autorisering/autentisering i Altinn2. 
Man gir tjenesten og en liste med mottakere og så slår kallet opp i databasen.
