### ISSUE TITLE
Overgangsløsning A2: BrokerBridge.GetFileDataByReference

### ISSUE THREAD

**Issue by RagnarFatland-Avanade** [Altinn/altinn-broker#252]
Implementer følgende metoder i BrokerBridge, med mapping mellom Altinn 2 datamodell og Altinn 3 datamodell.
Anbefaler at denne er første oppgave etter å ha etablert BrokerBridge, da man kan gjøre første mapping mellom A3-representasjonen av en BrokerFile og A2.

- [x] Metode: GetFileDataByReference
  Aksjoner:
  - [x] Kall GET broker/api/legacy/v1/file/{fileId}
  - [x] Map om til Altinn 2 BrokerServiceFileBE.

Siden dette blir første kall på tvers må det etableres en Maskinportenklient i BrokerBridge, man kan basere seg på eksisterende IMaskinportenHttpClientWrapper.

Dersom det viser seg at nødvendige felter ikke er tilgjengelig i angitt A3 kall, kan isteden man se om det er nødvendig å bruke GET broker/api/legacy/v1/file/{fileId}/details
Dersom det også skulle vise seg å være ufullstendig, tar vi en diskusjon om hvordan vi løser det på best måte og evt. legger till de aktuelle feltene i A3.
- [x] Vurder å legge til felter i A3-modell

**Comment by RagnarFatland-Avanade** [comment]
Har kommet i gang i A2-kodebasen og har en røff førsteversjon klar, samt at jeg identifiserte 3 felter som kan vurderes å legges inn i A3-modellen av ikke bare rent tilbake-kompatible årsaker:
- [ ] File.BrokerServiceResourceId
  - Unik id for tjenesten. I Final versjon vil det være samme verdi/felt som Resource_id i Ressurs Registeret
- [ ] File.FileSize - Filstørrelse i bytes
- [ ] File.SentDate / CreatedDate
  - Kan egentlig utledes fra FileStatusHistory man får fra broker/api/legacy/v1/file/{fileId}/details, men siden denne operasjonen er mer omfattende så kan det vurderes å legge dette til i modellen allerede på nivå for Overview.

**Comment by RagnarFatland-Avanade** [comment]
Felter lagt til i PR #283 
Jobber videre med resten

**Comment by RagnarFatland-Avanade** [comment]
Har bedt @tomshag følge opp denne inntil jeg er tilbake på jobb.
Altinn 2 delen krever bare litt cleanup og testing.
Altinn 3 delen får auteniseringsfeil pga ugyldig test-token; må generere ett korrekt ett, samt at tilsynelatende får en uhåndtert feil uten at jeg ser hvordan. Har en unit test som fremprovoserer feilen.

**Comment by tomshag** [comment]
@RagnarFatland-Avanade 
Da skal Altinn 2 delen være klar, og en pull request er blitt opprettet:
https://dev.azure.com/digdir/Altinn/_git/Altinn/pullrequest/6640

Gjorde følgende endringer:
La inn altinn.config test verdier
La inn ny External type for Status Enum for Recipient, denne viste tidligere til et objekt som så refererte til seg selv. I resultatet i Altinn 3 så returneres kun en Enum der.
Endret på mapper kode, la inn mapping på enkelte verdier som manglet og som trengtes for full utførsel av GetFileOverview.
La inn unittester for GetFileDataByReference
(1 som returnerer fildata og en som ikke returnerer data.)

**Comment by RagnarFatland-Avanade** [comment]
Ferdigstilt endringer for A3 i PR #288 
I A2 i PR: https://dev.azure.com/digdir/Altinn/_git/Altinn/pullrequest/6661
