### ISSUE TITLE
Overgangsløsning A2: BrokerBridge.Download + ConfirmDownloaded

### ISSUE THREAD

**Issue by RagnarFatland-Avanade** [Altinn/altinn-broker#255]
Implementer følgende metoder i BrokerBridge.
- [x] DownloadFile
  - GET broker/api/legacy/v1/file/{fileId}/download
- [x] ConfirmDownloaded
  - POST broker/api/legacy/v1/file/{fileId}/confirmdownload}

**Comment by RagnarFatland-Avanade** [comment]
Utføres etter #252

**Comment by tomshag** [comment]
Denne er nå ferdig i både Altinn 2 og Altinn 3
