### ISSUE TITLE
Støtte for konfigurering av virusscan per tjeneste

### ISSUE THREAD

**Issue by Ceredron** [Altinn/altinn-broker#273]
**Beskrivelse**

Virusscan er en funksjon som enkelte av kundene våre trenger, men ikke alle. Vi må derfor legge til støtte for å konfigurere det på tjenestenivå.

Noen ønsker dette for å: kunne sende ende-til-ende kryptert, eller for å støtte større payloads og throuhgput mellom tiltrodde parter.

Ettersom Microsoft Defender er aktivert for en hel storage account om gangen fordrer det at vi oppretter to storage accounts per tjeneste-eier istedenfor en. En med virusscan og en uten. Vi må også legge til logikk som sikrer at filer lagres til riktig storage account avhengig av tjenesteoppsett. 

Vi har allerede støtte for flere lagringsmedier per tjeneste-eier i form av StorageProvider-tabellen. Bygg videre på den.

- [ ] Automatisk deploy av to storage accounts; en med virusscan og en uten. Se AzureResourceManagerService.cs.
- [ ] Lagring av fil til riktig storage account
- [ ] Støtte for å opprette og endre en tjeneste med virusscan påslått. (Se ServiceController.cs)
- [ ] #529

**Comment by Ceredron** [comment]
Avventer juridisk/risikovurdering for om konfigurerbar virusscan er noe vi skal tillate.

**Comment by leogasnier** [comment]
@Oddhild - slik jeg tolker det så kan vi tillate å "skru av" virusscan teknisk uten problem (bør være på som default), og så må vi vurdere hvor lett eller vanskelig det skal være. Mulig filer sendt uten virusscan burde "merkes"?! Tanker?

**Comment by benedicteos** [comment]
Vurdering av hvordan vi ivaretar ende-til-ende kryptering, og eventuelle avvik fra krav, må Sikkerhet gjennomføre.  @leogasnier

**Comment by leogasnier** [comment]
Update fra avklaringsissue:
Vi kan tilby dette kun til tjenesteeiere som kan vise til en god begrunnelse og  ROS.
Rutine må beskrives på confluence og docs.
Å skru av virusscan skal ikke kunne gjøres uten vår "godkjenning".

**Comment by Ceredron** [comment]
https://github.com/Altinn/altinn-broker/issues/525
Duplikat av denne
