### ISSUE TITLE
Teknisk integrasjonsguide V1

### ISSUE THREAD

**Issue by Ceredron** [Altinn/altinn-broker#277]
**Beskrivelse**

Vi trenger en integrasjonsguide som gir nok informasjon for at noen skal kunne bygge en Altinn 3 integrasjon. Denne guiden bør inkludere enten en guide eller en referanse til en annen guide for:

- [ ] Flyt-diagram som viser en typisk filoverføringsprosess fra initiering til sletting.
- [ ] Opprette Maskinporten tjeneste
- [ ] Samples for spørringer (informasjon om bearer token, eksempel på initiate kall)
- [ ] Håndtere events (subscription etc)
- [ ] Groome https://github.com/Altinn/altinn-broker/issues/244 

Andre ting som kan vente til senere versjoner:
* FAQ
* Edge cases

Integrasjonsguiden skal utvides og forbedres over tid så scopet på denne oppgaven kan begrenses til det som er nødvendig for en enkel integrasjon mot broker-API'et. 

**QA**

- [ ] Test at du kan følge den blindt fra A til Å.
- [ ] Test at Altinn Assistant i den eksterne Altinn-slacken svarer på spørsmål fra dokumentasjon på en spørring som "Hvordan integrerer jeg mot Broker-API'et.

**Comment by leogasnier** [comment]
Husk å se denne opp mot og gjenbruk fra: https://docs.altinn.studio/app/#get-started

**Comment by leogasnier** [comment]
Mulig denne guiden bør inneholde litt rundt miljøer - lokal, tt02 og prod?!
