### ISSUE TITLE
Brøytetesting av overgangsløsning

### ISSUE THREAD

**Issue by RagnarFatland-Avanade** [Altinn/altinn-broker#309]
Gi støtte til Altinn 2 test team i deres test av overgangsløsning / BrokerBridge mot LegacyFileController.
De har skissert følgende test-scenario:

- [x] Test the Brokerservice end-to-end flow with multiple recipients(both Org and SSN) and sender where broker service is configured with Altinn 3 config
- [x] Regression : Test the Broker Service end-to-end flow with multiple recipient using org number as sender
- [x] Run Regression on existing BrokerService with Feature toggle = off
- [x] Run Regression on existing BrokerService with Feature toggle = on
- [x] Regression : Test broker service with end-to-end flow via SOAP Request
- [x] Negative : Verify it gives error message when file is not uploaded while initiating broker service

Aktuelle receipients/senders trenger ikke settes opp i Altinn 3 pga implisitt trust i LegacyFileController.
Dersom man i tillegg vil teste via vanlig FileController mot de samme filene, så må derimot de konkrete brukerene defineres. 

Denne testen skal gi input til/groome #312

**Comment by RagnarFatland-Avanade** [comment]
Altinn 2 testerne har satt opp en egen BrokerService selv med ACN som serviceowner, noe som ikke eksisterer i Altinn 3, men kan nok brukes likevel.
> TUL og har migrert i AT24. Det er den : Broker_Service_with_Altinn3
> service code 4678
>service edition code er : 4947

Vi har også satt opp med TTD som serviceowner som er tilsvarende serviceowner vi vil bruke i Altinn 3.
"Team Formidling" i TUL med tjenestekode 6010. Den har en utgave (1) som bruker SRR. Krever UTINN-rollen. Migrert til TT02."

Vi har satt opp i aktuell ressurs i Ressurs registeret til formålet:
- altinn-broker-test-resource-2
Det bør være mulig å mappe begge A2 tjenestene til den samme A3-tjenesten.

**Comment by tomshag** [comment]
Da er brokerbridge brøytetestet ok.
Fant et par gjenstående bugs som det er levert pull request for. Disse bug-ene var ikke sperrende ihht. testing.
