### ISSUE TITLE
Ikke-funksjonelle krav - omsette til backlogg

### ISSUE THREAD

**Issue by leogasnier** [Altinn/altinn-broker#31]
https://docs.altinn.studio/technology/architecture/requirements/non_functional/

**Comment by leogasnier** [comment]
Utover det som er beskrevet på lenke over må vi gjøre avklaringer mot sikkerhet, og jus mtp. etterlevelse og ev. standarder vi skal følge.
Krav til driftbarhet/forvaltbarhet/statistikk/fakturagrunnlag ol. kan også komme til her.

**Comment by leogasnier** [comment]
Ad- betaling: La oss ta et lite møte med Vidar og Viktor

**Comment by ToreMasoy** [comment]
Dekkes av #42 og #91, samt nytt sett av epics.
