### ISSUE TITLE
Legg til resource owner tag på Azure-ressurser

### ISSUE THREAD

**Issue by Ceredron** [Altinn/altinn-broker#311]
**Beskrivelse**

For å støtte tjeneste-eier granulert fakturering bør vi merke Azure-ressursene med en identifikator for tjeneste-eier. Det er ikke landet noen felles standard ennå, men inntil videre kan vi legge inn:
resourceOwnerOrgNo (org nummer på standard form (dvs med, 0192: prefix for Norge))

**Comment by Andreass2** [comment]
Gjør vi ikke allerede dette da vi legger inn orgnr med prefix som en tag både på storage account og på resource group?
