### ISSUE TITLE
Dokumentasjon av overgangsløsning

### ISSUE THREAD

**Issue by RagnarFatland-Avanade** [Altinn/altinn-broker#312]
Dokumentasjon må produseres for overgangsløsningen og publiseres i Altinn docs

- [x] Overordnet forklaring av teknisk løsning
- [x] Begrensinger i bruk for både A2 og A3-konsumenter
- [x] Eksempler
- [x] Hva må TE utføre for å ta den i bruk
- [ ] Gjennomgang/skrivebordstest med kartverket

**Comment by leogasnier** [comment]
Må bygge på/gjenbruke integrasjonsguiden: #277

**Comment by tomshag** [comment]
Soft shift altinn 2 to altinn 3:
https://docs.altinn.studio/broker/solution-architecture/#soft-shift-from-altinn-2-to-altinn-3

**Comment by leogasnier** [comment]
Mulig å hente noe tekst herfra: https://digdir.sharepoint.com/:w:/r/sites/MeldingogFormidling/Delte%20dokumenter/General/Altinn%20migrering/Formidling/Kommunikasjon/Brev%20til%20tjenesteeiere%20om%20endringer%20i%20Altinn%20Formidling.docx?d=w113b295590ae4576a9adbe921b54a52a&csf=1&web=1&e=Dr9oB1

**Comment by tomshag** [comment]
Dokumentasjon er nå utført, og oversettelse er gjort. Avventer review av oversatte dokumenter.

**Comment by tomshag** [comment]
Dokumentasjon utført, review utført, dokumentasjon merget inn i master.
