### ISSUE TITLE
Legg inn støtte for systembrukere

### ISSUE THREAD

**Issue by Ceredron** [Altinn/altinn-broker#316]
**Beskrivelse**

Avventer at systembrukere blir implementert i plattform.
https://github.com/Altinn/altinn-authentication/issues/331

For bekskrivelse av hva systembruker er:
https://docs.altinn.studio/authentication/systemauthentication/

Det eneste vi må gjøre er å dokumentere det samt legge til systembruker id og system id i PDR'en vi sender til Altinn Autorisasjon.

**Comment by leogasnier** [comment]
Bør støtte for bruk av RRR også inn her (en slags whitelist over godkjente aktører på en ressurs/tjeneste)? Nødvendig med endringer på vår side? Bør nok inn i vår docs som et minimum.

**Comment by leogasnier** [comment]
Konferer med Rune TL eller Jon Kjetil før det startes på denne - for å avklare hva som er klart når.

**Comment by leogasnier** [comment]
https://github.com/Altinn/altinn-authentication/issues/200

**Comment by ToreMasoy** [comment]
Venter på RRR

**Comment by RagnarFatland-Avanade** [comment]
Har vi en konkret Issue hos RRR vi kan lenke til @ToreMasoy ?

**Comment by Ceredron** [comment]
Avventer implementasjon over sommeren. Sjekk igjen i august.

**Comment by RagnarFatland-Avanade** [comment]
Blitt duplisert av #576 ??

**Comment by leogasnier** [comment]
Ser sånn ut @RagnarFatland-Avanade - vi bør vel slå de sammen.
