### ISSUE TITLE
Malware scan feil bør logge mer detaljerte feilmeldinger.

### ISSUE THREAD

**Issue by RagnarFatland-Avanade** [Altinn/altinn-broker#338]
Alle feil rapportert ved Malware scan blir bare logget som "Malware scan failed" - enten pga. filstørrelse eller pga. faktisk Malware.
Det bør logges/rapporteres mer detaljerte årsaker slik at det blir synliggjort og muliggjør mer detaljert feilsøking, både i vanlig logg og FileTransferStatusEvents.

Som en del av testingen av denne endringen kan man analysere hvordan Microsoft Defender håndterer for store filer;
Scan begynner når filen er ferdig opplastet. Det er mulig den bare ser på filstørrelsen og aborterer øyeblikkelig. I så tilfelle vil filen bare saneres, men det bør bekreftet.
Spørsmålet er om vi dette skaper unødvendig last og kostnader.
I så fall kan det bety vi bør gjøre størrelsesbegrensing-sjekk i vår løsning før filene trigger Malware-scanning.

**Comment by Andreass2** [comment]
Det ser ut til at vi allerede logger all data fra malware scan internt. 
Men jeg har endret til at vi logger litt mer detaljert informasjon ut til tjenesteeiere. 

ift. feil ved størrelse er det ikke lenger ett problem da bruker får tilbakemelding om filstørrelse før virusscan og lagring til Storage. Dermed trengs heller ikke sanitering.

**Comment by Andreass2** [comment]
Det kom opp spørsmål om hvordan man håndterer filer ved funn av virus. 

Er orginalfilene noe som burde beholdes, for å f.eks som bevis i noe juridisk (Vise at det ikke er falske positiver)
Eller kan saniteringsjobb starte med en gang. 

Hører videre med Stephanie  i studio

**Comment by Andreass2** [comment]
Tilbakemelding fra studio var at dette er noe de ikke har tatt stilling til, og at filer saniteres relativt raskt. 
De fokuserte på rask tilbakemelding til tjenesteeier og det har vi også. 


Leo hører videre med Jurist.

**Comment by leogasnier** [comment]
https://docs.altinn.studio/broker/80.-security/20-summary-of-security-controls/#virus-check

**Comment by Andreass2** [comment]
Jeg oppdaterer litt på dokumentasjon før jeg sender den videre til done. 

Forresten, Vi har ikke implementert at virusscan er  konfigurerbar enda.

**Comment by leogasnier** [comment]
Bra, vet, og jeg er vel litt i tvil om det skal være mulig på instansnivå?! Kan jo fort bli litt kaotisk rundt hva som er scannet og ev. ikke, så du kan godt moderere den formuleringa som ligger der inntil videre :)

**Comment by Andreass2** [comment]
Jeg tenker vi utfyller den informasjonen når vi har bestluttet hvordan vi gjør det forettningsmessig. 
Det blir nok 2 ulike storages for filene,  så tror det skal gå helt fint å ha kontroll selv om de kan velge det på instansnivå

**Comment by Andreass2** [comment]
https://github.com/Altinn/altinn-studio-docs/pull/1483
