### ISSUE TITLE
Skriv om Terraform til Bicep

### ISSUE THREAD

**Issue by Ceredron** [Altinn/altinn-broker#343]
**Beskrivelse**

Bicep er brukt av andre team og virker å være the "way forward". Dialogporten har allerede gått for det, og de har allerede laget en del pipelines som passer med det. Så vi kan like godt bare omskrive vår først som sist nå som vi går public med infrastrukturkoden ettersom vi uansett bør reviewe alt nøye.

Følg konvensjoner fra Dialogporten så langt det er hensiktsmessig.

**Comment by Andreass2** [comment]
The code that needs review is inside the .github and .azure folders + the readme file
