### ISSUE TITLE
Feil ved opplastning av flere filer

### ISSUE THREAD

**Issue by Andreass2** [Altinn/altinn-broker#348]
### Description of the bug

Ved kjøring av ytelsestest feiler ca 1 av 20 concurrent opplastninger på en fil med ca. størrelse 45 mb.
Dette må testes i testmiljø.  

Feilmelding:
Request Failed                                
error=wsarecv: Et tilkoblingsforsøk mislyktes fordi den tilkoblede parten ikke svarte på riktig måte etter en tidsperiode, eller den etablerte tilkoblingen mislyktes fordi den tilkoblede verten ikke svarte.

Det er ikke trigget noen feil i selve API'et 

### Steps To Reproduce

1. Fiks testfile.txt til å være ca 45 mb
2. MOCK respons fra Altinn Authorization, Altinn Register service, Altinn ResourceRegister og EventBus så det slipper å bli unødvendig last på deres testmiljø. 
3. Kjør ytelsestest mot testmiljø. 
4. Kan prøve med ulike verdier av VUS og iterations i test.

**Comment by Ceredron** [comment]
Kjørte test og avbrøt etter ca 500 sekunder:
k6-test-1  | running (08m22.8s), 20/20 VUs, 351 complete and 0 interrupted iterations
k6-test-1  | default   [   4% ] 20 VUs  08m22.6s/10m0s  00351/10000 shared iters
Nettlinja var på 280mbit opp så det er som forventet.

Tidligere tjenestebrudd kan ha vært forårsaket av andre utviklere (les meg 😅) kan ha jobbet i testmiljøet samtidig. Mener jeg jobbet med storage accounten og malwarescan på det tidspunktet.

Fikk ikke interruption, men ved testing av lavere filstørrelse fikk jeg lavere ytelse enn forventet. Tester videre.

**Comment by Ceredron** [comment]
Filstørrelse 2mb:
k6-test-1  | running (01m20.5s), 00/20 VUs, 500 complete and 0 interrupted iterations
k6-test-1  | default ✓ [ 100% ] 20 VUs  01m20.3s/10m0s  500/500 shared iters

Gitt den tidligere testen med 45mb filer skulle vi forventet at båndbredden setter en grense på 15/s for 2mb fil. Men det ender opp med å ta mer enn dobbelt så lang tid. 

k6-test-1  | running (04m34.8s), 0/5 VUs, 500 complete and 0 interrupted iterations
k6-test-1  | default ✓ [ 100% ] 5 VUs  04m34.6s/10m0s  500/500 shared iters

k6-test-1  | running (00m43.9s), 00/40 VUs, 500 complete and 0 interrupted iterations
k6-test-1  | default ✓ [ 100% ] 40 VUs  00m43.7s/10m0s  500/500 shared iters



Har testet endel mer og spunnet ut følgende oppgaver:
#356 
#358

**Comment by Ceredron** [comment]
Fant annen bug og spant ut #359 .
