### ISSUE TITLE
Tjenestekonfigurator i GUI: Altinnstudio

### ISSUE THREAD

**Issue by leogasnier** [Altinn/altinn-broker#350]
Vi må avklare om broker skal "full-integreres" i studio eller om vi bare skal lage en app for konfig av formidlingstjeneste.

Jeg heller mot at vi bør fullintegreres da det gir fordeler knyttet til oppsett mot ressursregisteret, et kjent interface for tjenesteutviklere som allerede er inne i studio, og gir mulighet for å bygge videre på GUI-komponenter for up/download for bruk av broker i andre produkter/settinger.

Ønsker at vi groomer denne ved å skaffe kompetanse på studio, hvordan tjenestekode forvaltes der, og får opp en anbefalt tilnærming til hvordan vi løser dette for broker. Som en del av den vurderingen må vi også kartlegge behov for endringer/hjelp fra team studio, og avklare muligheten for å få det, og når.
```[tasklist]
### Tasks
- [ ] analyse
```

**Comment by Andreass2** [comment]
Etter samtale med studio. 

De oppretter en epic på en konfigurasjonstjeneste i studio, hvor vi legger inn litt ekstra spesifikasjoner.  Fokus på hva er bare minimum for første versjon. Vi må nok ta hovedansvar for utviklingen, men de kan bidra med hjelp. 
Selve tidssestimering og scope tar vi en samtale på etter epic er opprettet og spesifikasjoner lagt inn.

**Comment by Andreass2** [comment]
https://github.com/Altinn/altinn-studio/issues/12530

**Comment by Andreass2** [comment]
Minimum Configuration Requirements has been made and given to Studio. (see https://github.com/Altinn/altinn-studio/issues/12531) 

I am also working on a document which specifies. 

full configuration Requirements and requriements for an application giving users functionality for download/upload etc.

**Comment by Andreass2** [comment]
Møte med gjennomgang av minimumskrav blir 3.4
