### ISSUE TITLE
Database connection exhaustion

### ISSUE THREAD

**Issue by Ceredron** [Altinn/altinn-broker#359]
**Beskrivelse**

Når vi lasttester med 50 VU og mer mot Postgres får vi etter hvert en del feilmeldinger. Disse ender opp i:
"remaining connection slots are reserved for non-replication superuser connections"
Som betyr at connection poolingen ikke virker.

Idag skal vi ha connection pooling på 25 ved at connection stringen vår inneholder "Maximum pool size = 25;" som skal være vel innenfor grensen på databasen som ligger på 100 samtidige connections.

En hypotese var at Hangfire kludret det til, men forsøkte å kjøre med UseMemoryStorage på Hangfire istedenfor Postgres slik at den ikke brukte databasen i det hele tatt. Da tålte den mer, men ved 100 VU fikk vi igjen skyhøye connection tall.

Logikken for connection handling ligger i DatabaseConnectionProvider.cs. Det er sannsynlig at feilen er å spore der.

**Comment by Andreass2** [comment]
Denne er nå testet og hovedproblemet har blitt fikset i og med at vi ikke lengre tilbake justerer fileTransfers utløpsdato ved endring av en ressurs lagringstid.

Fant en feil angående sletting av filer som førte til: #389  + en liten justering i Health Controlleren
