### ISSUE TITLE
pilottesting av teknisk integrasjonsguide

### ISSUE THREAD

**Issue by Andreass2** [Altinn/altinn-broker#361]
Pilottesting av teknisk integrasjonsguide.

**Comment by Andreass2** [comment]
Step 3. 
- Det burde linkes til dokumentasjon om våre events når den blir ferdig utfylt.

**Comment by Ceredron** [comment]
> Step 0. Burde vi ha en intern guide på hvordan vi får tak i subscription key?
> 
> Edit med svar fra Roar: Prosedyren i dette tilfellet vil bli at vi spør Simon Ellefsen om å generere en og så sender vi (eller han) den til kunden. Men siden vi allerede har en subscription key kan vi hoppe over det steget

Håper å få noe bedre på plass her etter hvert, men det blir sannsynligvis ikke løst før vi har et team med fullt eierskap over APIM. Det er planlagt noe der sentralt.

**Comment by Ceredron** [comment]
> Step 2.
> 
> * Burde vi linke til resource registry's dokumentasjon. Om de oppretter en ressurs så er vell det noe som skal/kan gjenbrukes i mange av altinns tjenester. Dermed fint å kunne linke til litt mer informasjon. Spesielt om Broker er en av de første tjenestene en ny kunde bruker
> * Postman collection link burde være første stedet det refereres, ikke siste. Alternativt begge steder. Litt usikker på om jeg synes den hører hjemme i Readme filen som hovedsakelig handler om lokal utvikling

Ja, jeg tenker det. Den er foreløpig ganske tynn, men det vil jo være "source-of-truth" på emnet.
https://docs.altinn.studio/api/resourceregistry/

Referansen til Postman-collectionen i steg 2 er for at de skal verifisere at de har riktige credentials. 
Det er ganske standard å ha Postman-collection i README.md.

**Comment by Ceredron** [comment]
> Step 3.
> 
> * Det burde linkes til dokumentasjon om våre events når den blir ferdig utfylt.
> * Foreslår å legge med scopene de trenger for events. Går utifra at de trenger både "altinn:events.subscribe" og "altinn:serviceowner"

Det er ingen av våre endepunkt som trenger noen altinn:events scopes lenger etter at vi gikk over til å bruke egen access token med altinn:events.publish.admin til å publisere. De trenger bare altinn:events.subscribe for kall mot Altinn Events, og de bør ikke ha det scopet i kallene mot oss.
