### ISSUE TITLE
Justering av utløpstid for eksisterende overføringer

### ISSUE THREAD

**Issue by Ceredron** [Altinn/altinn-broker#376]
**Beskrivelse**

Hva skal skje med eksisterende filoverføringer når utløpstiden endres? Vi har per nå logikk som justerer eksisterende filoverføringer. Denne ble utilsiktet ødelagt i en nylig oppdatering. Men bør vi gjøre det?
Hvis ikke, slett eksisterende logikk for det. Hvis vi vil ha det slik må vi sørge for at det logges på en god måte slik at det er lett å ettergå.

**Comment by Andreass2** [comment]
Jeg la merke til at koden som gjør selve slettingen bruker resource.FileTransferTimeToLive og ikke fileTransfer.Expiration time. 
Dermed vil nå sletting ikke skje på riktig tidspunkt før denne blir gjort

**Comment by RagnarFatland-Avanade** [comment]
I Altinn 2 så blir Expirytime satt under Initialize-steget og kalkulert med tilsvarende FileTransferTimeToLive på det tidspunkt. Evt. endring av FileTranferTimeToLive i etterkant ikke påvirker Expiry på allerede initialiserte FileTransfers.
Jeg syntes vi skal beholde denne tankegangen, da FileTransfer.Expiration er et nyttig fakta som bør være lett tilgjengelig, og ikke bør måtte kalkuleres på nytt ved hvert oppslag.
Dersom vi får et konkret behov for at endring i Resource.FileTransferTimeToLive skal medføre endring av Expiration for eksisterende FileTransfer, så kan vi nok legge inn en update-operasjon som en del av endringen i Resource.FileTransferTimeToLive, kanskje parameterstyrt "updateExistingFileTransfers".
