### ISSUE TITLE
Sett opp Slack-varsel til vaktordningen for ukjente feil

### ISSUE THREAD

**Issue by Ceredron** [Altinn/altinn-broker#378]
**Beskrivelse**

Når appen vår møter på uforutsette feil kaster den en 500-feilmelding. Det skal aldri skje og bør debugges omgående. Vi bør sette opp Slack varsel fra App Insights slik at vi får det inn i #team-melding-formidling når dette skjer.

Pass på at vi har noen form for rate limiting så vi ikke blir spammet.

**Comment by Andreass2** [comment]
Tenker en god idè vil være å opprette en ny slack kanal for alerts, noe ala det dialogporten har gjort.

**Comment by Andreass2** [comment]
Etter samtale med Eirik Mikkelsen endres denne til å sette opp ett system som varsler vaktordningskanelene på slackkanalene for vaktordningen.
