### ISSUE TITLE
Inviter til faste møter med tjenesteeiere, interessenter og brukere hver 14. dag.

### ISSUE THREAD

**Issue by leogasnier** [Altinn/altinn-broker#39]
Tjenesteeiere +++
 Mål med møtet - presentere det vi har gjort i sprint og få tilbakemeldinger på det umiddelbart.

**Comment by CWO79** [comment]
Denne er vel i prosess? Forslag til invitasjon og agenda er laget, to datoer før ferien er spikret. Venter på endelig godkjenning fra Leo før jeg kan publisere arrangementet. 

Møteserie fra august skal også landes før vi tar ferie.

**Comment by ToreMasoy** [comment]
Første møte 16. juni klokka 12:00

**Comment by CWO79** [comment]
Arrangementer 16 og 30 juni er publisert på Digdir sine sider.

**Comment by CWO79** [comment]
Invitasjon er også sendt på e-post til våre eksisterende kunder og samarbeidspartnere:

"Som en oppfølging av våre tidligere samtaler ønsker vi å invitere dere til å følge arbeidet med migreringen av Altinn Formidling, og etter hvert Altinn Melding over til nye løsninger. Vi setter stor pris på den interessen dere har vist, og ønsker å holde dere oppdatert på fremdrift og utvikling.

Derfor arrangere vi åpne møter hver 14. dag, hvor dere kan følge prosessen, stille spørsmål og dele deres synspunkter. 

Vi håper dere setter av tiden til å delta sånn at vi kan sikre at alle som trenger det får den nødvendige informasjonen. Tips gjerne andre relevante kollegaer eller samarbeidspartnere som kan ha interesse av å følge prosjektet. 

Vi rekker to møter for sommerferien. Dere finner mer informasjon på Digdir sine sider: 
Møte #1: [16 juni](https://www.digdir.no/felleslosninger/apent-mote-altinn-formidling-og-melding/4685) 
Møte #2: [30 juni](https://www.digdir.no/felleslosninger/apent-mote-altinn-formidling-og-melding/4687) 
 
Agenda for det første møtet: 
•            Velkommen 
•            Situasjon og bakgrunn 
•            Kort oppsummering av innsiktsarbeidet 
•            Åpen mikrofon - Har vi riktig forståelse av behov? 
•            Tentativ fremdriftsplan 
•            Spørsmål og innspill"
