### ISSUE TITLE
Analyse av overvåkningsløsning og varsling.

### ISSUE THREAD

**Issue by Andreass2** [Altinn/altinn-broker#406]
### Description

Det er ett ønske om at varsling og overvåkning blir gjort på tvers av alle produkter. 
Team plattform er i gang for å se på dagens opplegg med nye øyne. 
Ta kontakt med Espen Herskedal for å høre om hvordan det skal gjøres.

**Comment by RagnarFatland-Avanade** [comment]
Denne kan lukkes, se #358 for videre arbeid.

**Comment by RagnarFatland-Avanade** [comment]
Denne kan lukkes, se #358 for videre arbeid.
