### ISSUE TITLE
Sikkerhetsmessig vurdering av foreliggende konseptalternativ

### ISSUE THREAD

**Issue by ToreMasoy** [Altinn/altinn-broker#42]

**Comment by leogasnier** [comment]
Avtalt møte med HansO og LIna for avklaringer rundt hvordan vi gjør denne vurderingen.

**Comment by ToreMasoy** [comment]
https://digdir.sharepoint.com/sites/Systemoversikt/SitePages/Hjemmeside.aspx?OR=Teams-HL&CT=1692860816663&clickparams=eyJBcHBOYW1lIjoiVGVhbXMtRGVza3RvcCIsIkFwcFZlcnNpb24iOiIyOC8yMzA3MDMwNzM0NiIsIkhhc0ZlZGVyYXRlZFVzZXIiOmZhbHNlfQ%3D%3D

**Comment by CWO79** [comment]
Sikkerhetsmessige vurderinger er gjort i løsnings dokumentasjonen på bakgrunn av trusselvurderinger i WS. Nødvendige sikkerhetskontroller er beskrevet.
