### ISSUE TITLE
500 error in legacy initialize file - status code cannot be set

### ISSUE THREAD

**Issue by Andreass2** [Altinn/altinn-broker#421]
### Description of the bug

For information about the error: 
https://portal.azure.com/#view/Microsoft_Azure_Monitoring_Alerts/AlertDetails.ReactView/alertId/%2Fsubscriptions%2F850a8842-269c-4a14-8fbe-af6b72e93075%2FresourceGroups%2Faltinn-broker-staging-rg%2Fproviders%2FMicrosoft.AlertsManagement%2Falerts%2F601e821c-9076-ac30-ccaa-d5a1b2ab0013

### Steps To Reproduce

1. Go to azure to see more information

**Comment by Ceredron** [comment]
Tested a few times, and it seems that this error should not occur with other types or error messages.
