### ISSUE TITLE
Juridisk vurdering av foreliggende konseptalternativ

### ISSUE THREAD

**Issue by ToreMasoy** [Altinn/altinn-broker#43]
I forbindelse med faseovergang fra konsept til plan, i porteføljeprosessen, må det foreligge en overodnet juridisk vurdering av konseptalternativene. 

Den foreløpige juridiske vurderingen er tilgjengelig i Teams. Før den juridiske vurderingen kan ferdigstilles må det foreligge skriftlig dokumentasjon av konseptet, inkl arkitekturskisser med tilhørende dokumentasjon. 

```[tasklist]
### Tasks
- [ ] https://github.com/Altinn/altinn-broker/issues/91
- [x] Ferdigstill overordnet juridisk vurdering for faseovergang @Oddhild @benedicteos
```

**Comment by leogasnier** [comment]
overordnet vurdering av konsept iht. porteføøljeprosessen: https://github.com/digdir/portfolio

**Comment by Oddhild** [comment]
Foreløpig juridisk vurdering er tilgjengelig i Teams: PG meldingsutveksling, mappen Altinn migrering og Juridisk

**Comment by ToreMasoy** [comment]
Avventer arkitekturskisser med mer før denne issuen kan lukkes.

**Comment by benedicteos** [comment]
Skriftlig dokumentasjon av arkitekturskissene, samt arkitekturskissene må foreligge før vi kan avslutte den juridiske vurderingen av konsept. (som et ledd i overgang av faser, den er overordnet, ref [Juridisk vurdering av konseptalternativ](https://digdir.sharepoint.com/:w:/r/sites/PGMeldingsutveksling/Delte%20dokumenter/General/Altinn%20migrering/Juridisk/Juridisk%20analyse%20av%20konsept%20for%20formidling.docx?d=we8429c6497ef4174bb98874f2ea2302c&csf=1&web=1&e=dfou93)

**Comment by benedicteos** [comment]
Jurister og arkitekt hadde en gjennomgang av eksisterende arkitekturdokumentasjon 20.11. Produkteier var i porteføljeråd for å flytte tiltak fra plan til implementering. 

Juridisk ga tilbakemelding til produkteier om at dokumentasjon slik arkitekt presenterte den for oss, var i en slik tilstand at det muliggjør videre samarbeid i teamet til å gjøre juridiske, tekniske og funksjonelle vurderinger/utredninger/analyser/beslutninger sammen.
