### ISSUE TITLE
Struktur docs.

### ISSUE THREAD

**Issue by leogasnier** [Altinn/altinn-broker#457]
Fixe struktur og menyer iht: https://github.com/Altinn/architecture-decision-log/issues/5 ref ark forum.

**Comment by erikhag1** [comment]
3. juni: Altinn Melding struktur oppdatert og på nett, klart for review
3. juni: Altinn Formidling struktur oppdatert, men har 25 broken links å fikse før det er på nett. Se branch erikhag1-20240601-3.

**Comment by erikhag1** [comment]
Altinn Formidling nå også oppdatert og på nett, klart til review.

**Comment by ToreMasoy** [comment]
Denne har vi i fellesskap gått gjennom og godkjent.
