### ISSUE TITLE
Risikoanalyse konseptvalg

### ISSUE THREAD

**Issue by leogasnier** [Altinn/altinn-broker#46]
Avklare form og innhold med HansO/styringsteam

DOD: Samle og oppsummere sikkerhetsvurdering, juridisk vurdering og risikoregister i et notat som anbefaler veien videre.

**Comment by CWO79** [comment]
Har begynt å tenke på struktur. Foreslår at vi tar utgangspunkt i målene våre.  https://digdir.sharepoint.com/:x:/r/sites/PGMeldingsutveksling/Delte%20dokumenter/General/Altinn%20migrering/Formidling/ROS-%20analyse%20kladd.xlsx?d=w8be77df17d6844a0a41be6b9ed9e7c94&csf=1&web=1&e=I67ALd

Foreslår videre at jeg tar ansvar for en overordnet ROS analyse, og at sikkerhetsvurdering og juridiske vurdering gjøres separat. Men at det blir en del av felles risikobilde.

**Comment by CWO79** [comment]
Opprettet møteserie med teamet. Risikoregister er opprettet.

**Comment by CWO79** [comment]
Gjennomført første møte, Tore, Benedicte og Erik var tilstede. 

Risikoregistret er opprettet, men de juridiske vurderingene  og sikkerhetsvurderingene ligger ikke inne. 

Til neste gang: 
Tore, Camilla og Leo går gjennom de organisatoriske risikoer for å lande på en fornuftig beskrivelse og legge til de vi føler mangler. Blant annet få inn tilgang på kompetanse. 

Benedicte og oddlaug legger inn de juridiske vurderingene

Erik legger inn risikoer knyttet til informasjonssikkerhet.

**Comment by CWO79** [comment]
Sikkerhetsmessige vurderinger er gjort, og rutine for mnd gjennomgang av risikoanalyse er etablert.
