### ISSUE TITLE
Bug: Trying to access delete blob in storage

### ISSUE THREAD

**Issue by Andreass2** [Altinn/altinn-broker#473]
[https://altinndevops.slack.com/files/USLACKBOT/F078DM8978S/2024_8_04_54_am](https://altinndevops.slack.com/files/USLACKBOT/F078DM8978S/2024_8_04_54_am?origin_team=T0TAC6NF3&origin_channel=C0TA707TR)

Status on fileTransfer should have been "Purged" and we should not have been trying to access the file.

**Comment by Ceredron** [comment]
This occurred because we migrated our Azure environment to a new one in relation to #401, and when doing so, the old environment kept running for a while and deleted the file without updating the new database. Hence we got inconsistent state and a 500 error.
