### ISSUE TITLE
Add NoSniff to X-Content-Type Header for all requests

### ISSUE THREAD

**Issue by Andreass2** [Altinn/altinn-broker#482]
Security risk V14.4.4 states that all requests should contain the X-Content-Type header with value "Nosniff". 

Should be added for both Broker and Correspondence.

**Comment by CelineTrammi** [comment]
Ser ut som det har blitt gjort i [correspondence](https://github.com/Altinn/altinn-correspondence/blob/b23ee38538dc55feb89e5cefb2b9947e6a678a60/src/Altinn.Correspondence.API/Helpers/SecurityHeadersMiddleware.cs#L15) og [broker](https://github.com/Altinn/altinn-broker/blob/57eef194d48f4ad23a3fab7771432addf826cd04/src/Altinn.Broker.API/Helpers/SecurityHeadersMiddleware.cs#L7) allerede med mindre jeg tar feil.
