### ISSUE TITLE
V1.12.2: Verify that user-uploaded files - if required to be displayed or downloaded from the application - are served by either octet stream downloads, or from an unrelated domain, such as a cloud file storage bucket. Implement a suitable Content Security Policy (CSP) to reduce the risk from XSS vectors or other attacks from the uploaded file.

### ISSUE THREAD

**Issue by Andreass2** [Altinn/altinn-broker#484]
We do se serve file downloads as octet stream, so no changes is needed regarding this. 

We are missing a Content Security Policy. Research and add a suitable CSP header to all requests.

This also affects "V14.4.3: " in https://github.com/Altinn/altinn-broker/issues/481 so mark that task as completed when done

**Comment by Ceredron** [comment]
Jeg er litt usikker på om vi kan implementere en god CSP gitt måten vi er brukt (som backend), eller om det er riktigere at det er Felles Arbeidsflate's CSP policy som gjelder. Jeg tror det er deres domene som vil kalle vårt API i så fall.

**Comment by Andreass2** [comment]
Leste litt om det og ser urelevant ut da vi kun tilbyr ett API. Om det er tilfellet så tenker jeg issue kan closes. Da har vi vurdert caset og konkludert med at det ikke blir relevant for vår del.

**Comment by Andreass2** [comment]
Konkluderte at dette er en setting som håndteres av frontend/webserver til frontendapplikasjonen
