### ISSUE TITLE
Docs - Produktfunksjonalitet

### ISSUE THREAD

**Issue by CWO79** [Altinn/altinn-broker#494]
Kapittel om produktfunksjonalitet må ferdigstilles for Altinn Formidling

Definition of done: Vi må ha en beskrivelse av hovedfunksjonene, og kommende store endringer vi har besluttet å lage. 

Struktur/ hvor skal det dokumenteres i docs:

1. Kapittel: "Hva får du?" Vi skal beskrive hva vi løser nå, men ikke hvordan vi løser det, se Altinn Studio for å finne struktur. 

2. Kapittel "Nyheter og planer": Her bør vi beskriver funksjonalitet (av en størrelse) som ligger i en definert sprint, under et samlepunkt som kan hete "kommende", se Studio. 
I tillegg til en opplisting av "levert"

Se på strukturen til Studio som vi ønsker å kopiere

**Comment by CWO79** [comment]
https://digdir.sharepoint.com/:w:/r/sites/MeldingogFormidling/Delte%20dokumenter/General/Altinn%20migrering/Melding/Overordnet%20produktbeskrivelse.docx?d=wfccb035a340a451abad1ceeabf82ea3d&csf=1&web=1&e=IXN7E7

**Comment by leogasnier** [comment]
denne kan lukkes. nyheter og planer dekkes i #517
