### ISSUE TITLE
Diverse analyseoppgaver Formidling

### ISSUE THREAD

**Issue by leogasnier** [Altinn/altinn-broker#51]
Med utgangspunkt i handoff fra Ragnar:

Status siste sprint
Den siste sprinten har gått mest til å få lest meg mer opp på Altinn 3 komponentene, samt hatt møter med Erik og andre arkitekter slik at konseptet kan masseres mer.
Jeg inkluderer derfor han på cc i denne mailen.
Jeg og Tom Sverre blant annet et godt møte med Terje Holene som har mye kunnskap rundt Events, Storage ol. og har videreformidlet mye av dette muntlig til Erik.

Noen viktige punkter som kan/bør følges opp i mitt fravær
Jeg har følgende, til dels ustrukturerte punkter som kan være nyttige å formidle, slik at det kan kikkes litt på i mitt fravær. – Jeg oppfatter at mye av dette er allerede på blokka til for eksempel Erik, men bedre sagt en gang for mye 😉
 
Dialogportens «rolle» mot komponenten vår.
Jeg og Erik diskuterte dette en del i går, og kjente behovet for ytterligere avklaringer her.
Det var for eksempel noe inkonsistens med hvordan API gjennom Dialogporten eller Direkte.
Vil det for eksempel medføre at noe av vår funksjonalitet skal struktureres på en besmt måte?
Vil våre API måtte følge en viss struktur for å tilgjengeliggjøres via Dialogporten
Hvor skal vi lagre «State» for en forsendelsesprosess? Via vår egen «storage-kompoenent» mot hver TE sin PostresSQL, direkte mot felles PostGresSQL fra vår egen komponent?
Vil RR / RRR kunne lagre konfig for en gitt formidlingstjeneste (saneringsregler osv.)? Eller må vi ha vårt eget lager for det?
Adressering:
Vil RRR-API kunne brukes for avsender til å verifisere om en ønsket mottaker har rett til motta direkte? Eller hente ut en liste over gyldige mottakere?
Eller bør vi lage et «skall»-kall i vårt API som bygger dette opp?
Events er i dag relativt knyttet til Altinn Studio Apps, men teamet jobber med å generalisere dem.
Events brukes også til å trigge nye prosess-steg inne i Altinn Apps i dag, noe som kan være aktuelt for oss ikke bare for å sende ut varslinger.
For eksempel Sanering per fil som trigges av Event for «Recipient Confirms Downloaded»/ «All Receipients Confirm Downloaded”
Hva er det beste måten å isolere det på for å unngå unødvendig ressursbruk og/eller transaksjonslåser?
Dagens Altinn Storage er for tett knyttet mot Altinn Studio Apps, så vi vil kunne ta noe av koden derfra, men strippe ned og tilpasse til vårt formål til en egen komponent.
Hvordan håndtere sanering når fil går ut på dato?
Må vi lage vår egen «periodisk ryddejobb»/batch ?
Kan vi bruke Events som trigges basert på dato ala det Terje snakket om på Varsling?
Hvordan skal vi strukturere kodebasen vår?
Eget Repo for hver «komponent»/Subkomponent?
 
Organisatoriske ting:
Det ble vel kort nevnt under forrige retro / kick-off at det kan være nyttig at vi får et par «mentorer» som jeg og Tom Sverre kan henvende oss til ved en del tekniske/praktiske spørsmål generelt sett rundt det å utvikle i Altinn 3-sfæren.
Mye av dokumentasjonen på Altinn Docs er rettet mot folk som skal utvikle Apps, ikke oss som skal utvikle nye komponenter. – Mulig det ligger en «developer handbook» jeg bare ikke har sett ennå?
Er det mulig å sikre «faste plasser» på Økern for de av oss som ønsker det?
Jeg ser at jeg nok vil ønske å sitte der 2-3 dager i uken, men føler at jeg sitter på litt «lånt plass» akkurat nå, ved at vi bare fant oss noen tomme plasser? Eller har jeg misoppfattet situasjonen.

Jeg håper ellers alle får tatt seg en god ferie i tur og orden og jeg er sikker på at Teamet får gjennomført en god prosess i mitt fravær 😊

**Comment by tomshag** [comment]
Dialogporten swagger:
https://dppoc-webapi.azurewebsites.net/swagger/index.html

**Comment by RagnarFatland-Avanade** [comment]
Oppdatert etter møte 15.08.2023 mellom @RagnarFatland-Avanade @tomshag @erikhag1 

	1. Dialogportens «rolle» mot komponenten vår.
Jeg og Erik diskuterte dette en del i går, og kjente behovet for ytterligere avklaringer her.
Det var for eksempel noe inkonsistens med hvordan API gjennom Dialogporten eller Direkte til våre API.
Vil det for eksempel medføre at noe av vår funksjonalitet skal struktureres på en bestemt måte?
Vil våre API måtte følge en viss struktur for å tilgjengeliggjøres via Dialogporten?
Vil Dialogporten gi oss logging?
	Action: Ser noe an etter møtet 16.08.

	2. Hvor skal vi lagre «State» for en forsendelsesprosess? 
Via vår egen «storage-kompoenent» mot hver TE sin PostresSQL, direkte mot felles PostGresSQL fra vår egen 
komponent?
	Isolert per tjenesteeier / tjeneste ?
	Action: Ragnar kikker videre på dette; avklarer.

	3. Vil RR / RRR kunne lagre konfig for en gitt formidlingstjeneste (saneringsregler osv.)? Eller må vi ha vårt eget lager for det?
		Nei, vi vil ha det i vårt store.
	
	4. Adressering:
Hvordan kan en konsument av FT koble til riktige API-endepunkter?
	Dialogporten?
	Manuelt oppgitt?
	Ressurs Registeret?
Hvordan kan vi tilby at avsender kan verifisere om en ønsket mottaker har rett til motta direkte? Eller hente ut en liste over gyldige mottakere?
	Disse dataene ligger i RRR?

Eller bør vi lage et «skall»-kall i vårt API som bygger dette opp?
Action: Tom Sverre kikker på dette, ta kontakt med Rune ifb. RR/RRR?

	5. Events
Events er i dag relativt knyttet til Altinn Studio Apps, men teamet jobber med å generalisere dem.
Events brukes også til å trigge nye prosess-steg inne i Altinn Apps i dag, noe som kan være aktuelt for oss ikke bare for å sende ut varslinger.
For eksempel Sanering per fil som trigges av Event for «Recipient Confirms Downloaded»/ «All Receipients Confirm Downloaded”
Hva er det beste måten å isolere det på for å unngå unødvendig ressursbruk og/eller transaksjonslåser?

Events kan brukes til å logge med?
Hvis man publiserer Events hele tiden og stykker opp løsningen i mange biter blir den fleksibel, men muligens dårlig performance.
Er events uavhengige eller er det predefinerte reiseruter/koregrafi per tjenesteinstans.
Action: Ragnar snakker litt mer med Terje om hvordan Events fungerer.

	6. Storage
Dagens Altinn Storage er for tett knyttet mot Altinn Studio Apps, så vi vil kunne ta noe av koden derfra, men strippe ned og tilpasse til vårt formål til en egen komponent.

	7. Sanering
Hvordan håndtere sanering når fil går ut på dato?
	Må vi lage vår egen «periodisk ryddejobb»/batch ?
	Kan vi bruke Events som trigges basert på dato ala det Terje snakket om på Varsling?
		Mye kost lite nytte? Da mesteparten er ryddet allerede?
		Kan "saner-pga-nedlastet" rydde "timeout-sanering"-eventen.
	Burde det produseres varslings-events for dette?
Action: Ragnar sjekker med Terje/Platform-teamet.

	7. Kodebase/Repo:
Hvordan skal vi strukturere kodebasen vår?
Eget Repo for hver «komponent»/Subkomponent?
Finnes det en mal vi kan følge?
Action: Ragnar sjekker med Erik Mikkelsen

	8. Organisatoriske ting:
Det ble vel kort nevnt under forrige retro / kick-off at det kan være nyttig at vi får et par «mentorer» som jeg og Tom Sverre kan henvende oss til ved en del tekniske/praktiske spørsmål generelt sett rundt det å utvikle i Altinn 3-sfæren.
Mye av dokumentasjonen på Altinn Docs er rettet mot folk som skal utvikle Apps, ikke oss som skal utvikle nye komponenter. – Mulig det ligger en «developer handbook» jeg bare ikke har sett ennå?
Action: Ragnar sjekker med Leo.

Er det mulig å sikre «faste plasser» på Økern for de av oss som ønsker det?
Jeg ser at jeg nok vil ønske å sitte der 2-3 dager i uken, men føler at jeg sitter på litt «lånt plass» akkurat nå, ved at vi bare fant oss noen tomme plasser? Eller har jeg misoppfattet situasjonen.
Action: Ragnar sjekker med Leo.

	9. Hosting av formidlingtjenesten
Nye "plattformtjenester" som hostes i sine egne Kubernetes-instanser?
Eller
En Kubernetes-innstans per TE/Formidlingstjenesteinnstans?
Eller begge deler?
Action: Ragnar sjekker med 

	10. Logging på tvers av hele prosessen?
CorrelationID

**Comment by RagnarFatland-Avanade** [comment]
Lukker denne generiske oppgaven og fordeler avklaringspunkter på epics/features.
