### ISSUE TITLE
CreateResource gives NPGSQL error

### ISSUE THREAD

**Issue by Andreass2** [Altinn/altinn-broker#515]
Jeg har opprettet en ny ressurs gjennom alltinn studio. "test-broker-resource-studio". 

Ved testing i TT02 miljø, fungerer ResourceRegistery kallene, samt service owner kallene. 
Ved initialisering av FileTransfer, oppstår følgene feil: 

Npgsql.PostgresException (0x80004005): 23503: insert or update on table "altinn_resource" violates foreign key constraint "altinn_resource_service_owner_id_fk_fkey"

Jeg vil anta at det skjer en feil hvor en service_owner har flere ressurser.

**Comment by Ceredron** [comment]
Jeg lurer på om dette kan være at man ved filinitialisering oppretter en resource-rad i databasen basert på outputten fra resource registry GET /resource-kallet. Der bruker man ServieOwnerId fra ressursdefinisjonen i resource registry som altinn_resource_service_owner som allerede må eksisterere i databasen (for at de riktige Azure-ressursene er provisjonert opp). 
Dvs, er det mulig at tjeneste-eieren som eier ressursen i ressursregisteret ikke har kalt /serviceowner? (f.eks om det er ttd som er tjeneste-eier)

**Comment by Andreass2** [comment]
Get request på service owner returnerer Altinn. Så service owner eksisterer i Broker

**Comment by Ceredron** [comment]
Det kan hende. Hva står som hasCompetentAuthority/organization i ressursdefinisjonen i resource registry?

**Comment by Andreass2** [comment]
Er dette noe vi bør validere/gi feilmelding på, gjennomføre en sjekk at resource matcher service_owner?

**Comment by Ceredron** [comment]
Jepp, dårlig feilmelding er en bug så denne bør vi fikse. Enig i fiksen. 

Jeg lurer også på om vi kanskje har dårlig feilmelding hvis man forsøker å sende på en ressurs som tilhører en service owner som ikke er registrert via /serviceowner så vi bør sjekke om vi trenger håndtering av det caset også.
