### ISSUE TITLE
docs: Få inn riktig frist, og skriv noe om større payload og ui-elementer

### ISSUE THREAD

**Issue by leogasnier** [Altinn/altinn-broker#517]
https://docs.altinn.studio/nb/broker/news-and-plans/ - trenger et lite løft.

Frist for flytting er 31.12.25

Lenke til release notes.

#375 - gui tjenestekonfigurasjon
#523 Egen issue for GUI på upload/download
#525  - Støtte for skikkelig store filer

(#83 - Epic)

...... - Støtte for payload >2gb (finner ikke issue?!).

**Comment by ToreMasoy** [comment]
Status @leogasnier ?

**Comment by leogasnier** [comment]
@CWO79 skulle se på denne mener jeg vi sa?

**Comment by erikhag1** [comment]
Dokumentasjon under "What's new?" for Altinn Formidling er oppdatert, med bruk av "nyhetskort" på linje med det som benyttes for andre produkter. NB: Dette krever oppdatering videre. Det finnes også rom for forberding i felles mal for "nyhetskort".
