### ISSUE TITLE
Støtte veldig store filer

### ISSUE THREAD

**Issue by Ceredron** [Altinn/altinn-broker#525]
**Beskrivelse**

Formidlingstjenesten skal kunne brukes til å overføre svært store filer. Inntil nå har vi vært begrenset til 2GB på grunn av virus scan, men vi har fått klarsignal for å kunne tillate overføring av filer uten scan gitt forbehold.

Vi må sørge for at GetFileOverview inneholder klar informasjon om at filen ikke er virusscannet. Vi må også finne ut hvor/når det skal konfigureres (per tjeneste? Per tjeneste-eier?).

Videre må vi teste og sikre at filoverføringen fungerer fint med svært store filer (100gb+). 
```[tasklist]
### Oppgaver
- [x] Skriv om datalag til å chunke bedre (upload/download)
- [x] Konstruer testoppsett for svært store filer
- [x] Skriv om API-lag til å støtte "optional" virusscan
- [x] Deploy storage account uten virus scan
- [ ] https://github.com/Altinn/altinn-broker/issues/529
- [x] Krev content-length på upload request
- [x] Optimaliser buffer-størrelser
- [x] Benchmarks
```

```[tasklist]
### Tester
- [x] 100GB Upload
- [x] 100GB Download
- [x] Buffer MD5
```

**Comment by leogasnier** [comment]
@CWO79 @erikhag1 - her kan vi beskrive behovet litt bedre inkl usecases og akseptansekriterier.

**Comment by Ceredron** [comment]
Løs bug med nedlastning av veldig stor fil i miljø
