### ISSUE TITLE
Konfigurerbar slettelogikk i formidlingstjenesten

### ISSUE THREAD

**Issue by leogasnier** [Altinn/altinn-broker#533]
**Beskrivelse**
Vi bør ha noe fleksibilitet i løsningen for når filer slettes. Blant annet er det greit med en karensperiode hvis man har flere undersystemer som skal motta samme filer via systembrukere.

CASE:

- DNB har flere systemleverandører for ulike aspekter av samme formidlingstjeneste.
- Behov for overlapp ved bytte av systemleverandør
- Ta ned behov for resending (som avvikshandtering)

---------------------------
Vi bør utvide ConfigureResource med de følgende feltene:
DeleteFileTransferAfterAllRecipientsConfirmed (bool) Default: true.
DeleteFileTransferGracePeriod (ISO8601 Duration format) Default: 2t, max 24t.

Deretter bør slettelogikken oppdateres slik at:
Hvis grace periode er definert bør den alltid hensyntas. Den fungerer slik at filen ikke blir slettet før "GracePeriod" tid etter at filoverføringen har fått status "AllConfirmedDownloaded".
Men hvis DeleteFileTransferAfterAllRecipientsConfirmed = true så gjelder ikke det fordi da vil man ikke kjøre noe slettelogikk etter at alle har bekreftet nedlastet. Da utgår filen istedet etter FileTransferTimeToLive.

Eksempler:
FileTransferTimeToLive = 30 for alle.
DeleteFileTransferAfterAllRecipientsConfirmed = True med mindre annet er nevnt.
DeleteFileTransferGracePeriod = NULL med mindre annet er nevnt.

Scenario 1A: (Dagens A3 impl uten ny funksjonalitet)
AllConfirmed etter 2 dager = > Fil slettes umiddelbart.

Scenario 1B:  (Dagens A3 impl uten ny funksjonalitet)
AllConfirmed inntreffer ikke før FileExpiry = > Fil slettes etter 30 dager (FileExpiry).

Scenario 2: Fil blir ikke confirmed
Uansett hva DeleteFileTransferAfterAllRecipientsConfirmed og DeleteFileTransferGracePeriod har for verdier, samme resultat;
Fil blir aldri Confirmed = > Fil slettes etter 30 dager.

Scenario 3: Normal-case?
DeleteFileTransferGracePeriod = 48 timer
AllConfirmed  etter 2 dager = > Fil slettes på dag 4.
Scenario 3: Ikke anbefalt
DeleteFileTransferAfterAllRecipientsConfirmed = False
AllConfirmed  etter 2 dager = > Fil slettes etter 30 dager (FileExpiry).

Scenario 4: Ikke anbefalt/ulogisk
DeleteFileTransferAfterAllRecipientsConfirmed = False
DeleteFileTransferGracePeriod = 48 timer
AllConfirmed  etter 2 dager = > Fil slettes etter 30 dager (FileExpiry)

Scenario 6: "Siste liten"
DeleteFileTransferAfterAllRecipientsConfirmed = True
DeleteFileTransferGracePeriod = 48 timer
AllConfirmed  etter 29 dager = > Fil slettes etter 31 dager.

**Comment by Andreass2** [comment]
Dette vil også medføre endringer på f.eks listen over statushistorikk. 

Skal det være mulig å Confirme filetransfer flere ganger? 
Skal vi logge hver nedlastning etter confirm? 

@leogasnier

**Comment by leogasnier** [comment]
Alle nedlastinger bør logges, og tenker det er naturlig at de som laster ned gir en confirm gitt at de ikke nødvendigvis vet om andre har lastet ned samme fil pva. Virksomhet?

Vennlig hilsen

Leo Sande Gasnier
Seniorrådgiver
Digitaliseringsdirektoratet


From: Andreas Hammerbeck ***@***.***>
Date: Tuesday, 3 September 2024 at 14:25
To: Altinn/altinn-broker ***@***.***>
Cc: Gasnier, Leo Sande ***@***.***>, Mention ***@***.***>
Subject: Re: [Altinn/altinn-broker] Konfigurerbar slettelogikk i formidlingstjenesten (Issue #533)
[ Ekstern e-post ]

Dette vil også medføre endringer på f.eks listen over statushistorikk.

Skal det være mulig å Confirme filetransfer flere ganger?
Skal vi logge hver nedlastning etter confirm?

@leogasnier<https://github.com/leogasnier>
