### ISSUE TITLE
Alltid returner application/json

### ISSUE THREAD

**Issue by Ceredron** [Altinn/altinn-broker#542]
**Beskrivelse**
Vi returnerer idag en ID når noen har opprettet en ressurs (f.eks en Broker filetransfer). Denne ID'en returnerer vi som "text/plain". Resultatet er at outputten blir:
`aa465467-2077-40e6-85e7-51b9912f889f`
I motsetning til oss returnerer Dialogporten sin id som application/json. Da blir returen seende slik ut:
`"aa465467-2077-40e6-85e7-51b9912f889f"`

Det er ikke noen helt klar standard for det, men jeg tenker at det er bedre å returnere samme content-type i alle endepunkt, og at vi dermed bør endre til application/json overalt. Åpen for motforestillinger.

```[tasklist]
### Tasks
```

**Comment by Andreass2** [comment]
Burde vi kanskje gått igjennom begge API`ene og definert tydeligere både for response og request objekter. 

F.eks på upload definerer vi hvordan data vi forventer å få, det gjør vi ikke andre steder: 

![Image](https://github.com/user-attachments/assets/b1635fc8-f819-4735-a2da-75833a7c5f7b)

**Comment by mSunberg** [comment]
Jeg har gått gjennom Broker og fikset avvikene der. Men vi har funnet noen bugs i Correspondance som hindrer testing av noen av API´ene, jobber videre med å fikse det her [https://github.com/Altinn/altinn-correspondence/issues/310](url)
