### ISSUE TITLE
Logge alle nedlastninger

### ISSUE THREAD

**Issue by Ceredron** [Altinn/altinn-broker#557]
**Beskrivelse**
Vi bør logge alle nedlastninger i Broker. Legg til DownloadStarted for hvert forsøk. Sørg også for at det er den "høyeste", ikke siste statusen som vises, i Overview request. Dvs, hvis en fil er lastet ned flere ganger, og bekreftes etter første forsøk, skal overview vise at den er confirmed selv om den også er lastet ned etterpå.

Skilt ut fra #539 
Ref:
"- Vi åpner nå for å laste ned filene flere ganger, skal vi logge alle nedlastninger? Jeg mener ja, det gir veldig mening. 

- I currentRecipientFileTransferStatusCode, skal vi da vise høyeste status eller nyeste status i overview request? Jeg mener høyeste status da det gjennspeiler "CurrentStatus", f.eks DownloadConfirmed"

**Comment by mSunberg** [comment]
Har gjort ferdig testing på denne nå. Alle nedlastinger blir logget og kan vises under details. Når man bruker overview er det alltid høyeste status som vises. 

Måtte bare oppdatere collection-fila til å bruke de nye feltene for grace period.
