### ISSUE TITLE
Tester for Resource controller kræsjer sporadisk

### ISSUE THREAD

**Issue by Andreass2** [Altinn/altinn-broker#563]
Vi har nå opplevd at testene for resourceController i Broker kræsjer sporadisk. 

Bruk tid på å analysere og finne ut hvorfor. 

Jeg fant ingen desverre ingen logger på det, men kan være lurt å teste både lokalt og gjennom git actions

**Comment by CelineTrammi** [comment]
Hmm, lokalt krasjer ikke ResourceController, men heller `MalwareScanResult` og `ServiceOwnerController`. Samme feilmelding som kom på ResourceController i test. Så må undersøke hva den feilen kommer av.

**Comment by CelineTrammi** [comment]
Race conditions... Veldig vanskelig å finne ut av når man ikke har umiddelbare tanker om hvor det ligger. Er ikke trivielt å replikere heller.

**Comment by Andreass2** [comment]
Lukkes pga duplikat av #585
