### ISSUE TITLE
Feil i InitializeFileTransfer

### ISSUE THREAD

**Issue by Andreass2** [Altinn/altinn-broker#586]
Det oppstår en PostgresError i når det opprettes en fileTransfer; 
23503: insert or update on table "altinn_resource" violates foreign key constraint "altinn_resource_service_owner_id_fk_fkey"

Se hele exception her: https://digdir.slack.com/archives/C07QHT7NKUY/p1731395399269239

**Comment by Ceredron** [comment]
Fra testbranch
