### ISSUE TITLE
Integrasjon med egne fagsystemer

### ISSUE THREAD

**Issue by erikhag1** [Altinn/altinn-broker#70]
## Users view

Title: **Integrasjon med egne  fagsystemer **
User role(s): Avsender; Mottaker
Users value statement(s): 
Ved å integrere med våre egne fagsystemer sikrer vi en sømløs, effektiv og automatisk dataflyt, noe som reduserer manuell inngripen, feilmarginer og operasjonelle kostnader. Dette styrker vår arbeidskapasitet, gir oss en raskere svarrate og forbedrer den generelle kvaliteten på tjenestene vi leverer. 

#### High level features (capabilities):
 * Støtte integrasjon (av Altinn formidling) med avsenders og mottakers  fagsystemer.
#### Additional information
TBD

```[tasklist]
### Features
- [ ] https://github.com/Altinn/altinn-broker/issues/135
- [ ] Standardløsning for integrasjon med sak/arkiv-systemer
- [ ] Andre standardintegrasjoner
```

```[tasklist]
### Work items

```

## Item attributes

_Note: Automatically updated properties, not intended for change by you;)_

_Issue type: epic_
_Concept no: 11_
_Stage: Onboarding_
_ArchiConceptID: id-78cab0d9690946c4b26ed8aea745ddf2_
_GithubIssueID: I_kwDOIwEQMM5vYMmG_

**Comment by erikhag1** [comment]
* Tom Sverre og Ragnar har analysert 
* Altinn Studio har API_er for hver app, mens Dialogporten parametrisreer….

**Comment by RagnarFatland-Avanade** [comment]
Grunnleggende funksjonalitet er implementert.
