### ISSUE TITLE
Interoperabilitet på tvers av sektorer, land og kommunikasjonsinfrastrukturer

### ISSUE THREAD

**Issue by erikhag1** [Altinn/altinn-broker#71]
## Users view

Title: **Interoperabilitet på tvers av sektorer, land og   kommunikasjonsinfrastrukturer**
User role(s): Tjenesteeier
Users value statement(s): 
TBD

#### High level features (capabilities):
 * Støtte interoperabilitet på tvers av sektorer, land og   kommunikasjonsinfrastrukturer
#### Additional information
TBD

```[tasklist]
### Features 
- [ ] Standarder for  integrasjon på tvers av sektorer og   kommunikasjonsinfrastrukturer (ref. EIF)
- [ ] Enhetlig arkitetekur
- [ ] API-er
- [ ] Nøkkelferdige systemintegrasjoner
```

```[tasklist]
### Work items

```

## Item attributes

_Note: Automatically updated properties, not intended for change by you;)_

_Issue type: epic_
_Concept no: 12_
_Stage: Onboarding_
_ArchiConceptID: id-a901d300dc464d8389e8c93ef9ba8e02_
_GithubIssueID: I_kwDOIwEQMM5vYMrX_

**Comment by RagnarFatland-Avanade** [comment]
Her trenger vi konkrete krav for å vurdere påvirkning.

**Comment by leogasnier** [comment]
Lukkes - aktuelle integrasjoner etableres ved behov.
