### ISSUE TITLE
Kansellere forsendelser

### ISSUE THREAD

**Issue by erikhag1** [Altinn/altinn-broker#72]
## Users view

Title: **Kansellere tidligere forsendelser **
User role(s): Avsender
Users value statement(s): 
TBD

#### High level features (capabilities):
 * Støtte for å kansellere forsendelser
#### Additional information
I de tilfeller der Avsender ved en feil sender en forsendelse, eller en enkeltfil til feil mottaker, er det behov for raskt å kunne kansellere forsendelsen før mottaker leser potensielt sensitivt innhold.
Kansellering innebærer at filen/forsendelsen umiddelbart blir utilgjengelig for mottakere.

```[tasklist]
### Features
- [ ] https://github.com/Altinn/altinn-broker/issues/280
```

```[tasklist]
### Work items

```

## Item attributes

_Note: Automatically updated properties, not intended for change by you;)_

_Issue type: epic_
_Concept no: 13_
_Stage: Operation_
_ArchiConceptID: id-7894b1b7e3f9484abc7ac64f4d811629_
_GithubIssueID: I_kwDOIwEQMM5vYMrr_

**Comment by RagnarFatland-Avanade** [comment]
Todo: @RagnarFatland-Avanade slå sammen med #73

**Comment by RagnarFatland-Avanade** [comment]
Burde Tjenesteeier og Forvaltning(oss) også kunne kansellere?

**Comment by leogasnier** [comment]
Må sees i sammenheng med risikovurdering og tiltak. Hva skal vi støtte teknisk og hvilke rutiner må vi ha?

**Comment by Ceredron** [comment]
Omgjort til User Story
