### ISSUE TITLE
Korrigere feil i tidligere forsendelser

### ISSUE THREAD

**Issue by erikhag1** [Altinn/altinn-broker#73]
## Users view

Title: **Korrigere feil  i tidligere forsendelser**
User role(s): Avsender
Users value statement(s): 
TBD

#### High level features (capabilities):
 * Formidle  beskjed om korrigering av feil i tidligere forsendelser
#### Additional information
TBD

```[tasklist]
### Features 
- [ ] Sporing med merking av versjoner av enkeltfiler som ugyldige/korrigerte
- [ ] Sporing med merking av versjoner av hele pakker som ugyldige/korrigerte
```

```[tasklist]
### Work items

```

## Item attributes

_Note: Automatically updated properties, not intended for change by you;)_

_Issue type: epic_
_Concept no: 14_
_Stage: Operation_
_ArchiConceptID: id-fa8f4ac87ca84c4db09f3180761820c6_
_GithubIssueID: I_kwDOIwEQMM5vYMsI_

**Comment by erikhag1** [comment]
Slå sammen med annen epic?

**Comment by RagnarFatland-Avanade** [comment]
Todo: @RagnarFatland-Avanade slå sammen med #72

**Comment by RagnarFatland-Avanade** [comment]
Slått sammen med #72.
