### ISSUE TITLE
Velge mellom å motta kun nye og  endrede dokumenter i en sak vs. hele dokumentsamlingen

### ISSUE THREAD

**Issue by erikhag1** [Altinn/altinn-broker#88]
## Users view

Title: **Velge mellom å motta kun nye og  endrede dokumenter i en sak vs. hele dokumentsamlingen**
User role(s): Mottaker
Users value statement(s): 
TBD

#### High level features (capabilities):
 * Formidle kun nytt og endret innhold, i stedet for hele samlinger av filer
#### Additional information
TBD

```[tasklist]
### Features 
- [ ] Lagring as a service (mot betaling)
- [ ] Versjonsmerking og tidsstempling av filer i en sak
- [ ] Annen  saksmappefunksjonalitet?
```

```[tasklist]
### Work items

```

## Item attributes

_Note: Automatically updated properties, not intended for change by you;)_

_Issue type: epic_
_Concept no: 29_
_Stage: Operation_
_ArchiConceptID: id-3acebbec2d6b43e69aa63e5c16e4bf41_
_GithubIssueID: I_kwDOIwEQMM5vYMx7_

**Comment by erikhag1** [comment]
NB: Juss
Husl Saneringsproblematikk
Dialogid
sak-dokumentsamling-dokument

**Comment by leogasnier** [comment]
droppes i denne runden
